default_config:

logger:
  default: info
  logs:
    custom_components.diffazur_hydrocapt: debug
    custom_components.integration_blueprint: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
#  start: true
#  wait: true
